%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FUNCTION: [fitresult, gof] = GMPEFit(Rhyp, ln_SA)
%
% SCRIPT NAME: createFit.m
%
% DESCRIPTION:
%   Performs a smoothing spline regression between the hypocentral distance 
%   (Rhyp) and the natural logarithm of spectral acceleration (ln_SA).
%   The script uses MATLAB’s Curve Fitting Toolbox and generates a visual 
%   fit along with residual plots.
%
%   This fitting procedure was developed as part of the doctoral research:
%   "Lessons Learned from the Survey of Damage to School Buildings by the 
%    Mw = 8.4 Illapel Earthquake (Chile, September 2015)"
%    Author: Juan Patricio Reyes Cancino
%    Doctoral Program in Earthquake Engineering and Structural Dynamics
%    Universitat Politècnica de Catalunya (UPC) – Universidad Austral de Chile (UACh)
%
% INPUT:
%   Rhyp   - Hypocentral distance [km] (vector)
%   ln_SA  - Natural logarithm of spectral acceleration [log(g)] (vector)
%
% OUTPUT:
%   fitresult - MATLAB fit object representing the smoothing spline model
%   gof       - Goodness-of-fit structure with statistical indicators
%
% DEPENDENCIES:
%   Requires MATLAB’s Curve Fitting Toolbox
%
% LICENSE: MIT License – See LICENSE_MIT.txt
%
% AUTHOR: Juan Patricio Reyes
% DATE CREATED: 2025-05-13
% LAST MODIFIED: 2025-05-19
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%function [fitresult, gof] = GMPEFit(Rhyp, ln_SA)
%CREATEFIT(RHYP,LN_SA)
%  Create a fit.
%
%  Data for 'Spline Fit' fit:
%      X Input: Rhyp
%      Y Output: ln_SA
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
%  Auto-generated by MATLAB on 13-May-2025 02:01:08


%% Fit: 'Spline Fit'.
% Cargar los datos
PGA_NS = [0.10
0.09
0.01
0.29
0.01
0.03
0.05
0.45
0.34
0.08
0.13
0.69
0.09
0.05
0.54
0.19
0.10
0.04
0.20
0.08
0.05
0.03
0.07
0.03
0.18
0.36
0.08
0.05
0.09
0.03
0.02
0.03
0.07
0.04
0.05
0.07
0.06
0.07
0.04
0.03
0.04
0.02
0.14
0.71
0.03
0.03
0.29
0.02
0.25
0.17
0.04];
PGA_EO = [0.09
0.11
0.01
0.31
0.01
0.05
0.06
0.47
0.24
0.08
0.07
0.55
0.11
0.05
0.45
0.19
0.14
0.03
0.27
0.08
0.05
0.04
0.13
0.03
0.15
0.34
0.04
0.06
0.09
0.03
0.02
0.03
0.06
0.05
0.04
0.06
0.05
0.10
0.03
0.04
0.06
0.02
0.09
0.83
0.04
0.03
0.35
0.02
0.19
0.25
0.04];
PGA=[
    0.17
0.15
0.01
0.47
0.02
0.06
0.09
0.67
0.44
0.13
0.15
0.91
0.15
0.08
0.78
0.28
0.19
0.06
0.36
0.12
0.07
0.05
0.16
0.04
0.26
0.52
0.10
0.08
0.15
0.05
0.03
0.05
0.11
0.06
0.07
0.10
0.08
0.13
0.05
0.05
0.08
0.04
0.17
1.19
0.05
0.05
0.49
0.03
0.36
0.34
0.06
];
ln_SA=[
-0.773366167
-0.816295175
-1.841402957
-0.329531844
-1.6745817
-1.20473531
-1.068323774
-0.173822359
-0.358755447
-0.902750215
-0.810289398
-0.042162477
-0.815941238
-1.11475898
-0.109874974
-0.55158386
-0.727514921
-1.256143918
-0.449070585
-0.917091886
-1.150837628
-1.31799648
-0.809625846
-1.351167341
-0.580238877
-0.283688599
-1.015959318
-1.074457076
-0.837983695
-1.335800901
-1.464468387
-1.338723211
-0.978282645
-1.194034469
-1.185477106
-0.989591127
-1.095918501
-0.889094165
-1.302991056
-1.26385496
-1.075573288
-1.434114172
-0.773290574
0.076448559
-1.262844384
-1.321222846
-0.306294899
-1.54997165
-0.440078477
-0.464683136
-1.221670364];
Rhyp = [168
163
384
164
395
244
230
181
183
235
182
89
263
229
135
235
191
298
148
124
168
235
183
231
195
100
177
246
211
260
263
241
241
250
165
226
168
256
202
239
234
378
167
128
242
228
137
165
183
206
244];
Rrup = [55
69
283
68
288
135
122
76
80
126
62
50
144
139
55
100
73
186
38
47
87
145
85
141
76
26
77
146
105
155
163
133
133
145
85
119
86
111
117
130
126
228
81
46
133
138
56
84
63
95
135];
Vs30 = [1106
323
715
1000
600
635
496
600
405
267
1228
751
1000
281
578
754
587
808
364
307
607
485
937
500
447
1000
1951
471
281
1127
727
724
370
577
882
347
212
600
549
574
353
583
596
626
647
477
704
854
737
600
1000];

% Crear tabla
T = table(log10(PGA(:)), Rrup(:), Vs30(:), ...
    'VariableNames', {'log10PGA', 'Rrup', 'Vs30'});



[xData, yData] = prepareCurveData( Rhyp, ln_SA );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Spline Fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'ln_SA vs. Rhyp', 'Spline Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Rhyp', 'Interpreter', 'none' );
ylabel( 'ln_SA', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'Spline Fit - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Rhyp', 'Interpreter', 'none' );
ylabel( 'ln_SA', 'Interpreter', 'none' );
grid on



